=== MatrixEditor/ubnt-discovery-tool/src/main/resources/com/ubnt/xml/iubntservice.dtd
<!-- DTD defining the import and export document structure-->
<!ELEMENT iubntservice (services)>
<!ELEMENT services (service*) >
<!ELEMENT service (address, interface, version, records)>

<!ELEMENT address (#PCDATA)>
<!ELEMENT interface (#PCDATA)>
<!ELEMENT version (#PCDATA)>

<!ELEMENT records (record*)>
<!ELEMENT record (#PCDATA)>

<!ATTLIST record
        type CDATA #REQUIRED
        class CDATA "String">

=== MatrixEditor/ubnt-discovery-tool/docs/example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE iubntservice SYSTEM "iubntservice.dtd">

<iubntservice>
    <services>
        <service>
            <address>127.0.0.1</address>
            <interface>eth0</interface>
            <version>1</version>
            <records>
                <record type="1">value</record>
                <record type="2" class="Number">1111</record>
                <record type="3" class="IpInfo">mac;ip</record>
            </records>
        </service>
    </services>
</iubntservice>
